kmer_size: 8
reference: "sliced_data/slice.fa"
vcf: "sliced_data/rebased_slice.vcf"

singularity_img: "/home/brice/Desktop/Gramtools/Singularity_Images/Images/4c39699_gramtools.img"

samples_dir: "/home/brice/Desktop/Projects/pop_run_gramtools/samples"
base_dir: "/home/brice/Desktop/Projects/pop_run_gramtools/runs"

quasimap_threads: 5
